### Test basic server connection
GET http://localhost:3000

###

### Test database connection
GET http://localhost:3000/test-db

###

### Get all users
GET http://localhost:3000/api/users

###


GET http://localhost:3000/api/users/1

###


POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "erik_johansson",
  "password": "secretpassword123"
}

###


POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "maria_nilsson",
  "password": "mypassword456"
}

###


POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "asa_oberg",
  "password": "svensklösenord789"
}

###


POST http://localhost:3000/api/users
Content-Type: application/json

{
  "password": "password123"
}

###


POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "weakuser",
  "password": "123"
}

###


POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "erik_johansson",
  "password": "differentpassword"
}

###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "alice_andersson",
  "password": "password123"
}

###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "bob_bengtsson",
  "password": "password456"
}

###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "nonexistent_user",
  "password": "anypassword"
}

###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "alice_andersson",
  "password": "wrongpassword"
}

###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "password": "password123"
}

###


POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "alice_andersson"
}



### Test - Create new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "oscar_test",
  "password": "testpassword123"
}

### Test - Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "oscar_test", 
  "password": "testpassword123"
}

### Get all users
GET http://localhost:3000/api/users
