services:
  login-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    env_file:
      - .env
    restart: unless-stopped
    container_name: login-api-container
